### ISSUE TITLE
Pax Instruments USB VID/PID to bootloader

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/ATmega32U4-bootloader#1]
The T400 and any other products based on the ATmega32U4 require a bootloader with the Pax Instruments USB VID and a PID unique to that product.

The bootloader in this repository should have the Pax Instruments USB VID and a PID designated to generic ATmega32u4 hardware development. This is to avoid collisions with released Pax Instruments products.

An USB VID application has been submitted on 2015-01-25.

**Comment by cibomahto** [comment]
Ok, need to know:
VID for Pax Instruments
PID for t400 bootloader
PID for t400 firmware (must be separate from the bootloader to avoid a windows bug)

**Comment by cibomahto** [comment]
I see VID=0x2B51
Can we use PID=0x1000 for T400 bootloader? Still need a second one for T400 firmware.

**Comment by charlespax** [comment]
Bootloader is 0x1000. Firmware is 0x1005.

**Comment by cibomahto** [comment]
K

**Comment by cibomahto** [comment]
Implemented in the bootloader in 178407f
