### ISSUE TITLE
T400 bootloader: enable power output pin at startup

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/ATmega32U4-bootloader#4]
Commented out in 6cabb63. Waiting for decision on power circuit changes.

**Comment by charlespax** [comment]
Sam is making changes to the power system (https://github.com/PaxInstruments/t400-electronics/issues/152).

**Comment by cibomahto** [comment]
Ok, it's enabled in 9cec31b. Will probably need to be revisited for the next rev

**Comment by cibomahto** [comment]
Modified this in c14d7102692c for the recommended change in Rev13:
https://github.com/PaxInstruments/t400-electronics/issues/184

**Comment by charlespax** [comment]
Everything seems to work in board revision 14.
